
russian_localization = {
    'global.quitConfirmation': u'Вы действительно хотите выйти?',
    'global.ok': u'OK',
    'global.quit': u'Выйти',
    'global.cancel': u'Отмена',
    'global.saveFile': u'Сохранить',
    'cocoa.menu.about': u'О приложении',
    'cocoa.menu.services': u'Сервисы',
    'cocoa.menu.view': u'Вид',
    'cocoa.menu.hide': u'Скрыть',
    'cocoa.menu.hideOthers': u'Скрыть остальные',
    'cocoa.menu.showAll': u'Показать все',
    'cocoa.menu.quit': u'Выйти',
    'cocoa.menu.fullscreen': u'Во весь экран',
    'windows.fileFilter.allFiles': u'Все файлы',
    'windows.fileFilter.otherFiles': u'Остальные типы файлов',
    'linux.openFile': u'Открыть файл',
    'linux.openFiles': u'Открыть файлы',
    'linux.openFolder': u'Открыть папку',
}